In [1]:
import numpy as np

Datatypes and Attribute

In [2]:
#numpy main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],
             [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3 = np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a3.shape

(2, 3, 3)

In [7]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [8]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [12]:
#creating a dataframe from a numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. Creating Arrays

In [13]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
ones.dtype

dtype('float64')

In [15]:
type(ones)

numpy.ndarray

In [16]:
random_array= np.random.randint(0,10, size = (3,5))
random_array

array([[0, 8, 5, 3, 0],
       [3, 6, 1, 4, 9],
       [4, 3, 0, 6, 7]])

In [17]:
random_array.size

15

In [18]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5,3))

In [28]:
random_array_2

array([[0.06563298, 0.74162258, 0.76616521],
       [0.0361463 , 0.45580298, 0.96354751],
       [0.20543989, 0.2177091 , 0.560351  ],
       [0.96787811, 0.06921233, 0.7581792 ],
       [0.00903173, 0.96856613, 0.88723839]])

In [62]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [63]:
random_array_4.shape

(5, 3)

In [70]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [71]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Viewing arrays in matrices

In [72]:
a1

array([1, 2, 3])

In [73]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
a3[0][0]

array([1, 2, 3])

In [77]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [80]:
a3[:2 , :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [81]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4
                                 

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [82]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [83]:
a4[:,:,:,:4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Manipulating and Comparing arrays

### Arithmetic

In [84]:
a1

array([1, 2, 3])

In [85]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [86]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [87]:
a1+ones

array([2., 3., 4.])

In [88]:
a1-ones

array([0., 1., 2.])

In [89]:
a1*ones

array([1., 2., 3.])

In [90]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [92]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [96]:
a2//a1

array([[1, 1, 1],
       [4, 2, 2]])

In [97]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [99]:
a2 % 2

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [100]:
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [101]:
np.log(a2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

## Manipuating array 2
### Aggregation

In [102]:
a1

array([1, 2, 3])

In [103]:
sum(a1)

6

In [104]:
np.sum(a1)

6

In [105]:
### let's create a massive array 
massive_array= np.random.random(100000)

In [106]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [107]:
%timeit sum(massive_array)  #python's sum()
%timeit np.sum(massive_array)  #numpy sum()

11.4 ms ± 36 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
72.5 µs ± 4.01 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [108]:
np.mean(a2)

3.5

In [109]:
np.sqrt(np.var(a2))

1.707825127659933

In [110]:
np.std(a2)

1.707825127659933

In [111]:
np.var(a2)

2.9166666666666665

### reshaping and transpose

In [112]:
a2


array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
a2.shape

(2, 3)

In [114]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [116]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [117]:
a2_reshape*a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [118]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
a2.T


array([[1, 4],
       [2, 5],
       [3, 6]])

In [120]:
a2.T.shape

(3, 2)

In [121]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [122]:
a3.shape

(2, 3, 3)

In [123]:
a3.T


array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [124]:
a3.T.shape

(3, 3, 2)

In [126]:
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1

array([[7, 7, 9],
       [8, 1, 5],
       [6, 5, 5],
       [8, 9, 3],
       [5, 0, 1]])

In [127]:
mat2

array([[0, 8, 1],
       [4, 8, 5],
       [5, 9, 9],
       [8, 6, 1],
       [7, 4, 1]])

In [128]:
#element wise or hadamard 
mat1*mat2

array([[ 0, 56,  9],
       [32,  8, 25],
       [30, 45, 45],
       [64, 54,  3],
       [35,  0,  1]])

In [129]:
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [133]:
mat_2 = mat2.T


In [134]:
mat_2

array([[0, 4, 5, 8, 7],
       [8, 8, 9, 6, 4],
       [1, 5, 9, 1, 1]])

In [135]:
mat_2.shape

(3, 5)

In [137]:
mat3=np.dot(mat1,mat_2)
mat3

array([[ 65, 129, 179, 107,  86],
       [ 13,  65,  94,  75,  65],
       [ 45,  89, 120,  83,  67],
       [ 75, 119, 148, 121,  95],
       [  1,  25,  34,  41,  36]])

In [138]:
mat3.shape


(5, 5)

In [195]:
np.random.seed(0)
sales_amount=np.random.randint(20,size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [196]:
sales_amount.shape

(5, 3)

In [198]:
weekly_sales=pd.DataFrame(sales_amount,index=["Mon","Tues","Wed","Thur","Fri"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [199]:
prices= np.array([10,8,12])
prices

array([10,  8, 12])

In [204]:
prices.shape

(3,)

In [206]:
Butter_prices=pd.DataFrame(prices.reshape(1,3),index=["Prices"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
Butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [277]:
Butter_prices.shape

(1, 3)

In [222]:
Tat=np.dot(sales_amount,prices)
Tat

array([240, 138, 458, 232, 142])

In [278]:
Tat.shape

(5,)

In [219]:
weekly_sales["Total ($)"]=Tat
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total  Total ($)
Mon              12             15              0    240        240
Tues              3              3              7    138        138
Wed               9             19             18    458        458
Thur              4              6             12    232        232
Fri               1              6              7    142        142

In [220]:
weekly_sales=weekly_sales.drop("Total",axis=1)
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon              12             15              0        240
Tues              3              3              7        138
Wed               9             19             18        458
Thur              4              6             12        232
Fri               1              6              7        142

In [218]:
Butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [223]:
a1

array([1, 2, 3])

In [224]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [226]:
a1<a2

array([[False, False, False],
       [ True,  True,  True]])

In [230]:
bool_array=a1>=a2
bool_array

array([[ True,  True,  True],
       [False, False, False]])

In [228]:
a1==a2

array([[ True,  True,  True],
       [False, False, False]])

In [232]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [235]:
random_array=np.random.randint(10,size=(3,5))
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [236]:
np.sort(random_array)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]])

In [238]:
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [237]:
np.argsort(random_array)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]], dtype=int64)

In [239]:
a1


array([1, 2, 3])

In [240]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [242]:
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [243]:
np.argmax(random_array,axis=0)

array([0, 2, 2, 1, 1], dtype=int64)

In [244]:
np.argmax(random_array, axis=1)

array([0, 3, 2], dtype=int64)

## Practical Example- Numpy in Action

In [256]:
from matplotlib.image import imread

In [260]:
panda = imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [261]:
from IPython.display import Image
Image(url= "panda.png", width=400, height=400)

In [262]:
print(type(panda))

<class 'numpy.ndarray'>


In [263]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [265]:
panda.size, panda.ndim, panda.shape

(24465000, 3, (2330, 3500, 3))

In [269]:
panda[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [270]:
a1

array([1, 2, 3])

In [271]:
a1.dtype

dtype('int32')

In [272]:
type(a3)

numpy.ndarray

In [276]:
np.random.seed(0)
np.random.random((5,3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [279]:
np.random.randn(3,5)

array([[ 0.48431215,  0.57914048, -0.18158257,  1.41020463, -0.37447169],
       [ 0.27519832, -0.96075461,  0.37692697,  0.03343893,  0.68056724],
       [-1.56349669, -0.56669762, -0.24214951,  1.51439128, -0.3330574 ]])

In [280]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])